name = "url-costom-link"
main = "src/index.js"
compatibility_date = "2026-02-01"
node_compat = true

[vars]
DOMAINS = "invdvvip.site"
ADMIN_KEY = "sesepuh17"

# Jika pakai KV (uncomment setelah membuat KV di dashboard)
[[kv_namespaces]]
binding = "LINKS_DB"
id = "cbe2c4e33d144ed3aaf8a3cd32b93f77" # Ganti dengan ID KV Anda

[build]
command = "npx wrangler"
